package shop.productSystem.beans;

public enum OperationSystem {
    NONE,WINDOWS_XP,WINDOWS_7,WINDOWS_8,WINDOWS_8_1,WINDOWS_10,LINUX_UBUNTU,LINUX_MINT,DOS,LINUX_MATE,MAC_OS,ANDROID,IOS,SYMBIAN,ENDLESS_OS
}
